language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t jwwisman/docker-vue -f Dockerfile.dev .

script:
  - docker run jwwisman/docker-vue npm run test -- --coverage